version: "3.9"  # optional since v1.27.0
# Services
services:
  # MongoDB
  mongodb:
    container_name: sirubot_mongodb
    ports:
      - "127.0.0.1:27017:27017"
    image: mongo:latest
    restart: always
    environment:
      # Change this to your credentials
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_datadir:/data/db
  # MariaDB
  mariadb:
    container_name: sirubot_mariadb
    ports:
      - "127.0.0.1:3306:3306"
    image: mariadb:latest
    restart: always
    environment:
      # Change this to your credentials
      MARIADB_ROOT_PASSWORD: super-secret-passwd
      MARIADB_DATABASE: siru
    volumes:
      - mariadb_datadir:/var/lib/mysql
  # SiruBOT Client
  sirubot:
    container_name: sirubot_discord
    build: .
    environment:
      - NODE_ENV=development
    command: node ./build -d -s -c settings.yaml
    volumes:
      - ./build:/opt/sirubot/build
      - type: bind
        source: settings.yaml
        target: /opt/sirubot/settings.yaml
    network_mode: host

# Volumes
volumes:
  mongodb_datadir:
  mariadb_datadir: