module.exports = {
  EMOJI_MUSIC: '🎵',
  EMOJI_NO: '❎',
  EMOJI_X: '❌',
  EMOJI_YES: '✅',
  EMOJI_HEART: '❤️',
  EMOJI_PINGPONG: '🏓',
  EMOJI_MONEY: '💸',
  EMOJI_STAR: '🌟',
  EMOJI_BULB: '💡',
  EMOJI_LOCALES: '🌏',
  EMOJI_WARN: '⚠️',
  EMOJI_BIN: '🗑️',
  EMOJI_HASH: '#️⃣',
  EMOJI_TRASHBIN: '🚮',
  EMOJI_PIN: '📌',
  EMOJI_COP: '👮',
  EMOJI_PERSON: '🙍',
  EMOJI_PAPER: '📃',
  EMOJI_HAMMER: '🔨',
  EMOJI_COMPUTER: '🖥️',
  EMOJI_SANDCLOCK: '⏳',
  EMOJI_WAVE: '👋',
  EMOJI_PAINT: '️🖼️',
  EMOJI_LABEL: '🏷️',
  EMOJI_JOYSTICK: '🕹️',
  EMOJI_ICEBLOCK: '🧊',
  EMOJI_ARROW_BACKWARD: '◀️',
  EMOJI_ARROW_TORWARD: '▶️',
  EMOJI_INFO: 'ℹ️',
  EMOJI_TIMER: '⏲️',

  EMOJI_KNOBS: '🎛️',
  EMOJI_MIC: '🎙️',
  EMOJI_SPEAKER: '🔊',
  EMOJI_AUDIO_NONE: '⏹️',
  EMOJI_AUDIO_PAUSED: '⏸️',
  EMOJI_AUDIO_PLAYING: '▶️',
  EMOJI_REPEAT_NONE: '➡️',
  EMOJI_REPEAT_ALL: '🔁',
  EMOJI_REPEAT_SINGLE: '🔂',
  EMOJI_SHUFFLE: '🔀',
  EMOJI_HEADPHONES: '🎧',

  EMOJI_REGIONS_BRAZIL: '🇧🇷',
  EMOJI_REGIONS_EUROPE: '🇪🇺',
  EMOJI_REGIONS_HONGKONG: '🇭🇰',
  EMOJI_REGIONS_INDIA: '🇮🇳',
  EMOJI_REGIONS_JAPAN: '🇯🇵',
  EMOJI_REGIONS_RUSSIA: '🇷🇺',
  EMOJI_REGIONS_SINGAPORE: '🇸🇬',
  EMOJI_REGIONS_SOUTHAFRICA: '🇿🇦',
  EMOJI_REGIONS_SOUTH_KOREA: '🇰🇷',
  EMOJI_REGIONS_SYDNEY: '🇦🇺',
  EMOJI_REGIONS_US_CENTRAL: '🇺🇸',
  EMOJI_REGIONS_US_EAST: '🇺🇸',
  EMOJI_REGIONS_US_WEST: '🇺🇸',
  EMOJI_REGIONS_US_SOUTH: '🇺🇸',

  EMOJI_SWITCH_ON: '<:emoji_on:649622462765596683>',
  EMOJI_SWITCH_OFF: '<:emoji_off:649622462685773884>',

  SUPPORT_SERVER: 'https://discord.gg/463PGcC',
  INVITE_URL: 'https://discord.com/oauth2/authorize?client_id=426722888293548032&scope=bot&permissions=8&response_type=code&redirect_uri=https%3A%2F%2Fchinobot.ga%2Fthanks',
  WEBPAGE: 'https://siru.moe',
  GITHUB: 'https://github.com/Sannoob/Siru-stable',
  PREFIX: '>>'
}
