# Typescript 빌드를 실행합니다

name: Typescript build

on: [pull_request] # push, pull request 가 발생했을때 작동합니다.
jobs:
  build:
    runs-on: ubuntu-latest # Ubuntu 최신버전에서 실행합니다

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Setup node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3 # actions/setup-node@v1 을 사용하여 Node.JS 버전을 설정합니다
      with:
        node-version: ${{ matrix.node-version }}
    -
      name: Install dependencies
      run: yarn install --production=false # yarn install 명령어로 개발 환경을 설정합니다
    
    -
      name: Run typescript build
      run: yarn run build:ts --noEmit # Typescript 프로젝트를 빌드합니다